=== yaronh12/CodeNames/out/production/engine/resources/CodeNames-v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ECN-Words">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ECN-Game-Words"/>
				<xs:element ref="ECN-Black-Words"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Team2">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="cards-count" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Team1">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="cards-count" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Layout">
		<xs:complexType>
			<xs:attribute name="rows" type="xs:int" use="required"/>
			<xs:attribute name="columns" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Game-Words" type="xs:string"/>
	<xs:element name="ECN-Game">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ECN-Words"/>
				<xs:element ref="ECN-Board"/>
				<xs:element ref="ECN-Team1"/>
				<xs:element ref="ECN-Team2"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Board">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ECN-Layout"/>
			</xs:sequence>
			<xs:attribute name="cards-count" type="xs:int" use="required"/>
			<xs:attribute name="black-cards-count" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Black-Words" type="xs:string"/>
</xs:schema>

=== yaronh12/CodeNames/engine/src/resources/classic (1).xml
<?xml version="1.0" encoding="UTF-8"?>
<ECN-Game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CodeNames-v1.xsd">
	<ECN-Words>
		<ECN-Game-Words>
encapsulation german poland kombat waffele whom leg character terms else camel rabbit fire text element sky item robot past dune dolphine then it am quality eye moon system folder light letter number notch allies dog word hash why gun pink what yellow sea see noon file top does ear can't table foot hand a strike black electricity pistol kill boat democracy off battle single fly component blue watch reflector future machine progress atom under inferno voice rotor tonight 	
		</ECN-Game-Words>
		<ECN-Black-Words>
mouce door data use doom sign screen do bomb red later whale white hello than which england morning dirt tree thrown water trash ranch she sand squad desk present where magenta game code enigma plural death vegtable fruit for their privacy back house fox not hair napkin and street cat now of iteration class trike fight mortal live how on patrol keyboard midnight or green umbrella wheel saw orange airplane window front		
		</ECN-Black-Words>
	</ECN-Words>
	<ECN-Board cards-count="24" black-cards-count="1">
		<ECN-Layout rows="5" columns="5"/>
	</ECN-Board>
	<ECN-Team1 name="T1" cards-count="9"/>
	<ECN-Team2 name="T2" cards-count="8"/>
</ECN-Game>
