=== yaronh12/CodeNames/engine/src/resources/CodeNames-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ECN-Teams">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ECN-Team" maxOccurs="6"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Team">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="guessers" type="xs:int" use="required"/>
			<xs:attribute name="definers" type="xs:int" use="required"/>
			<xs:attribute name="cards-count" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Layout">
		<xs:complexType>
			<xs:attribute name="rows" type="xs:int" use="required"/>
			<xs:attribute name="columns" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Game">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ECN-Dictionary-File" type="xs:string"/>
				<xs:element ref="ECN-Board"/>
				<xs:element ref="ECN-Teams"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ECN-Board">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ECN-Layout"/>
			</xs:sequence>
			<xs:attribute name="cards-count" type="xs:int" use="required"/>
			<xs:attribute name="black-cards-count" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yaronh12/CodeNames/engine/src/resources/big.xml
<?xml version="1.0" encoding="UTF-8"?>
<ECN-Game name="tough love" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../Downloads/CodeNames-v2.xsd">
	<ECN-Dictionary-File>moby dick.txt</ECN-Dictionary-File>
	<ECN-Board cards-count="60" black-cards-count="4">
		<ECN-Layout rows="15" columns="4"/>
	</ECN-Board>
	<ECN-Teams>
		<ECN-Team name="T1" cards-count="8" definers="3" guessers="4"/>
		<ECN-Team name="T2" cards-count="6" definers="2" guessers="3"/>
		<ECN-Team name="T3" cards-count="6" definers="2" guessers="2"/>
		<ECN-Team name="T4" cards-count="4" definers="1" guessers="1"/>
	</ECN-Teams>
</ECN-Game>
